title: "Select an Option"
#cmd: "docker run -it --rm -v $PWD:/app -w /app $1:$2"

# TODO make it possible
#vars: # Variables for Array of Blocks which can be reused
#  - tags:
#      - value: 'alpine',
#        display: 'Alpine latest',
#        color: "blue"
#
#      - value: '1.23-alpine'
#        display: "Alpine 1.23"
#        color: "blue"

# TODO make the sorting work again (map is random)

blocks:
  - display: "Temp Container"
    color: "Blue"
    cmd: "docker run -it --rm -v $PWD:/app -w /app $2:$3"
    title: "Select an Image"
    blocks:
      - value: "golang"
        display: "GoLang"
        color: "BlueBright"
        title: "Select a Version"
        blocks:
          - value: 'alpine'
            display: 'Alpine latest'
            color: "Yellow"

          - value: '1.23-alpine'
            display: "Alpine 1.23"
            color: "Blue"


      - value: "alpine"
        display: "Linux"
        color: "Green"
        title: "Select a Version"
        blocks:
          - value: 'latest'
            display: 'Alpine latest'
            color: "BlueBright"

          - value: '1.23-alpine'
            display: "Alpine 1.23"
            color: "Blue"


  - value: "go-build"
    display: "GO Build"
    color: "Red"
    cmd: "docker run -t --rm -v $PWD:/app -w /app -e GOARCH=amd64 -e GOOS=$2 golang:alpine go build"
    title: "Select a Target-OS"
    blocks:
      - value: "linux"
        display: "Linux/amd64"
        color: "Green"

      - value: "windows"
        display: "Windows/amd64"
        color: "MagentaBright"


  - value: "others"
    display: "Others"
    title: "Select an Option"
    blocks:
      - display: "Some"
        color: "Green"

      - display: "More"
        color: "MagentaBright"

      - display: "Options"
        color: "Cyan"
