title: "Select a Thing"
cmd: "docker run -it --rm -v $PWD:/app -w /app golang:alpine"
#cmd: "docker run -t -v $PWD:/app -w /app -e GOOS=windows -e GOARCH=amd64 golang:alpine go build"

#vars: # Variables for Array of Blocks which can be reused
#  - tags:
#      - value: 'alpine',
#        display: 'Alpine latest',
#        color: "blue"
#
#      - value: '1.23-alpine'
#        display: "Alpine 1.23"
#        color: "blue"


blocks:
  - value: "golang"
    display: "GoLang"
    color: "BlueBright"
    title: "Select a Version"
    blocks:
      - value: 'alpine'
        display: 'Alpine latest'
        color: "Yellow"

      - value: '1.23-alpine'
        display: "Alpine 1.23"
        color: "Blue"

  - value: "alpine"
    display: "Linux"
    color: "Green"
    title: "Select a Version"
    blocks:
      - value: 'latest'
        display: 'Alpine latest'
        color: "BlueBright"

      - value: '1.23-alpine'
        display: "Alpine 1.23"
        color: "Blue"

  - value: "go-build"
    display: "GO Build"
    color: "Red"
    cmd: "docker run -t --rm -v $PWD:/app -w /app -e GOARCH=amd64 -e GOOS=$2 golang:alpine go build"
    title: "Select a OS"
    blocks:
      - value: "linux"
        display: "Linux/amd64"
        color: "Green"

      - value: "windows"
        display: "Windows/amd64"
        color: "MagentaBright"



