name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # triggers SemVers Tags

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [ linux, windows ]
        goarch: [ amd64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-X 'main.Version=${{ github.ref_name }}'" -o selto-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: selto-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./selto-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: selto-linux-amd64

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: selto-windows-amd64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            selto-linux-amd64
            selto-windows-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}